### PR TITLE
Create convertMarkdown.sh

### PR DESCRIPTION
**Pull request by XertroV**

### CODE REVIEW

**Comment by XertroV** [comment]
note - this is a script to aid in auto conversion of markdown to other formats

**Comment by Oliver-Minter** [comment]
Good or Evil?

On 31 Oct 2018 8:40 PM, "Max Kaye" <notifications@github.com> wrote:

note - this is a script to aid in auto conversion of markdown to other
formats

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/voteflux/flux/pull/33#issuecomment-434621876>, or mute
the thread

**Comment by XertroV** [comment]
@Oliver-Minter see https://github.com/voteflux/flux-website-v2/pull/76 and let me know :)

will eventually live at voteflux.org/constitutions.html

or https://flux-constitutions.s3.amazonaws.com (though that is ugly AF)

**Comment by XertroV** [comment]
note - planning to add notifications via SNS + SES (email) soon with subscriptions (which can be filtered by filename so you only get updates for a single branch, for example)

**Pull request merged**
