### PR TITLE
New Steer Co Members + typos

### PR DESCRIPTION
**Pull request by BrainOnBread**
The Steering Committee members: Nick Dorogavtsev as Party Agent, Brent Abel as Secretary, Deb Robins as D.R.O. and a few typos changed.

### CODE REVIEW

**Comment by XertroV** [comment]
@BrainOnBread - I think it's probably better if we don't alter the constitution for this stuff since the constitution only needs to set up initial steerco members, etc. Better is to document in @voteflux/flux-docs on a per-branch basis.

@voteflux/flux-docs-team / @pwhipp - can we get a section for branches w/ a super basic template + section for steerco members + rolls that'll be easy to edit?

**Comment by pwhipp** [comment]
@XertroV : Yes, although I think the  constitution may also need an update to point to the branch document index.
Can I have a couple of examples of the branch content? - I'll derive the template from those and add them as actual branches.

**Comment by XertroV** [comment]
@pwhipp - I don't think the constitutions need updating - we can just add it to the README (note: constitution changes are best avoided if possible due to reporting requirements, etc. if it doesn't _need_ to be in there it probs shouldn't be)

Structure of branches section:

- Branches
  - Aus
  - NSW
  - VIC
  - ACT
  - QLD
  - WA

For each branch:
  - Policies
  - Status
  - SteerCo and Positions held

We can add other stuff as we go

**Comment by pwhipp** [comment]
@BrainOnBread: I've integrated your changes directly into the new structure [here](https://docs.flux.party/en/latest/docs/branches/qld/index.html).  They will probably benefit from more input from you. If you fork [flux docs](https://github.com/voteflux/flux-docs) you can submit changes as a new PR. Feel free to contact me directly for help with using restructured text rather than markdown (or to translate any of your markdown to rst - pandoc does a pretty good job of that).

@XertroV: I've merged the [branches/constitution sections](https://docs.flux.party/en/latest/docs/branches/index.html) to keep the hierarchy as simple as possible. It looks like the constitution document includes the steerco. I've added blank templates for 'Policies' and 'Status' to the QLD branch. These can be copied to the other branches as needed.

If you are both happy with this we can deprecate this pull request because its content is accounted for and continue the discussion either in new PRs or in issues.

**Pull request merged**
